# Generated by Django 5.1.6 on 2025-03-01 20:08

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='body',
            field=tinymce.models.HTMLField(default='Conteúdo do projeto', verbose_name='Conteúdo do Projeto'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(default='projects/covers/default.jpg', upload_to='projects/covers/', verbose_name='Capa do Projeto'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_info',
            field=models.CharField(default='Breve descrição do projeto', max_length=500, verbose_name='Informação Breve'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Novo Projeto', max_length=200, verbose_name='Título'),
        ),
    ]
